### ISSUE TITLE
License Info

### ISSUE THREAD

**Issue by realeyesmedia** [riedlse/scte35#1]
Hi, what is the current licensing you wish to have applied to this repo / codebase? Since there is none, by default, we have to follow Github's TOS

> Making your GitHub project public is not the same as licensing your project. Public projects are covered by GitHub’s Terms of Service, which allows others to view and fork your project, but your work otherwise comes with no permissions.
> 
> If you want others to use, distribute, modify, or contribute back to your project, you need to include an open source license. For example, someone cannot legally use any part of your GitHub project in their code, even if it’s public, unless you explicitly give them the right to do so.

Is the intent to remain unlicensed?

**Comment by riedlse** [comment]
Decided to use BSD 3-clause

**Comment by riedlse** [comment]
Note, I do have som eender versions of this code that bring it up to the current 2019 SCTE 35, although I have not updated this repository yet, I may get to that in a month or two when I leave Turner.

**Comment by jgainfort** [comment]
Noted that you want BSD 3. Do you plan to add a license file to the repo?

**Comment by riedlse** [comment]
I thought I did that and the license is added


I’ll probably update the code in the next week or two for the latest rev of the standard.
—
Steven Riedl
steve@superiorswimtiming.com
(720) 279-4895 (Google Voice)
www.superiorswimtiming.com
